//! Instantiate a module, call functions, and read exports.

use crate::{
    capi_executor::{CapiExecutor, vm_exec_executor_t},
    service_singleton::with_service,
    string_copy, vm_exec_result_t,
};
use libc::{c_char, c_int};
use meta::capi_safe_unwind;
use multiversx_chain_vm_executor::{CompilationOptionsLegacy, InstanceLegacy};
use std::convert::TryFrom;
use std::sync::atomic::{AtomicBool, Ordering};
use std::slice;

/// Maximum bytes scanned when converting a C-string function-name
/// pointer into a Rust `&str`. Wasm function names in real contracts
/// are 4-32 chars; 1024 is generous and bounds the worst-case scan if
/// the C caller violates the null-terminator contract.
const MAX_C_FUNC_NAME_LEN: usize = 1024;

/// Reads a bounded null-terminated C string and validates UTF-8.
///
/// Previously the executor used `CStr::from_ptr` which walks the
/// pointer until it encounters a null byte, with no length cap. A C
/// caller passing a buffer without a null terminator caused an
/// unbounded read that could (a) leak adjacent heap contents into the
/// returned slice (and from there into log strings via
/// update_last_error_str), or (b) walk into unmapped memory and
/// segfault.
///
/// This helper uses `libc::strnlen` to find the null terminator while
/// guaranteeing the scan never crosses MAX_C_FUNC_NAME_LEN bytes —
/// strnlen's contract is "scan at most n bytes for null", so unlike
/// strlen it will not walk into adjacent allocations or unmapped
/// pages. The subsequent slice creation uses only the discovered
/// length so it cannot over-read either.
///
/// # Safety
///
/// `ptr` must be a valid pointer to readable memory. strnlen's
/// contract caps the read at MAX_C_FUNC_NAME_LEN bytes from `ptr`,
/// but the caller must still ensure those bytes are within an
/// allocation it owns; passing a stack pointer to a 2-byte buffer
/// without a null inside it is undefined behaviour for the strnlen
/// call itself. The C API consumer (mx-chain-vm-go) constructs these
/// pointers from heap-allocated strings with a guaranteed null, so
/// in practice the contract is satisfied.
unsafe fn read_bounded_c_str<'a>(ptr: *const c_char) -> Result<&'a str, String> {
    let n = unsafe { libc::strnlen(ptr, MAX_C_FUNC_NAME_LEN) };
    if n >= MAX_C_FUNC_NAME_LEN {
        return Err(format!(
            "function name is not null-terminated within {MAX_C_FUNC_NAME_LEN} bytes"
        ));
    }
    let bytes = unsafe { slice::from_raw_parts(ptr as *const u8, n) };
    std::str::from_utf8(bytes).map_err(|err| format!("invalid function name utf-8: {err}"))
}

/// Opaque pointer to a `wasmer_runtime::Instance` value in Rust.
///
/// A `wasmer_runtime::Instance` represents a WebAssembly instance. It
/// is generally generated by the `wasmer_instantiate()` function, or by
/// the `wasmer_module_instantiate()` function for the most common paths.
#[allow(non_camel_case_types)]
#[repr(C)]
pub struct vm_exec_instance_t;

#[allow(non_camel_case_types)]
#[repr(C)]
pub struct vm_exec_compilation_options_t;

pub struct CapiInstance {
    pub(crate) content: Box<dyn InstanceLegacy>,
    /// Race-protection flag for `vm_exec_instance_destroy`.
    ///
    /// **What this protects against:** two threads calling
    /// `vm_exec_instance_destroy` concurrently on the same pointer
    /// *before* `Box::from_raw` has run. `compare_exchange` with
    /// `Ordering::AcqRel` ensures only one thread wins the race to
    /// reclaim the Box; the loser observes `destroyed == true` and
    /// returns without touching the allocation.
    ///
    /// **What this does NOT protect against** (audit re-validation
    /// correctly downgraded this to "Mostly Fixed / Not Confirmed
    /// Closed"): a *second* destroy call from a *single thread*
    /// after the first destroy has completed. The first destroy
    /// frees the allocation via `Box::from_raw`. The second destroy
    /// then reads the flag through `&*(instance_ptr as *const ...)`
    /// — but that read dereferences freed memory, which is
    /// undefined behaviour regardless of what value happens to be
    /// observed. The atomic flag *requires* the memory to still be
    /// valid to be read.
    ///
    /// A complete close requires the handle-based API redesign
    /// (audit Open Finding #3) where instance "pointers" become
    /// `CapiInstanceId(u64)` indices into a generation-counter pool
    /// validated by the runtime before each dereference. That is
    /// tracked as separate future work.
    pub(crate) destroyed: AtomicBool,
}

/// Creates a new VM executor instance.
///
/// All of the context comes from the provided VM executor.
///
/// # Safety
///
/// C API function, works with raw object pointers.
#[allow(clippy::cast_ptr_alignment)]
#[unsafe(no_mangle)]
#[capi_safe_unwind(vm_exec_result_t::VM_EXEC_ERROR)]
pub unsafe extern "C" fn vm_exec_new_instance(
    executor_ptr: *mut vm_exec_executor_t,
    instance_ptr_ptr: *mut *mut vm_exec_instance_t,
    wasm_bytes_ptr: *mut u8,
    wasm_bytes_len: u32,
    options_ptr: *const vm_exec_compilation_options_t,
) -> vm_exec_result_t {
    let capi_executor = cast_input_ptr!(executor_ptr, CapiExecutor, "executor ptr is null");

    if wasm_bytes_ptr.is_null() {
        with_service(|service| service.update_last_error_str("wasm bytes ptr is null".to_string()));
        return vm_exec_result_t::VM_EXEC_ERROR;
    }

    let wasm_bytes: &[u8] =
        unsafe { slice::from_raw_parts(wasm_bytes_ptr, wasm_bytes_len as usize) };
    let compilation_options: &CompilationOptionsLegacy =
        unsafe { &*(options_ptr as *const CompilationOptionsLegacy) };
    let instance_result = capi_executor
        .content
        .new_instance(wasm_bytes, compilation_options);
    match instance_result {
        Ok(instance_box) => {
            let capi_instance = CapiInstance {
                content: instance_box,
                destroyed: AtomicBool::new(false),
            };
            unsafe {
                *instance_ptr_ptr =
                    Box::into_raw(Box::new(capi_instance)) as *mut vm_exec_instance_t;
            }
            vm_exec_result_t::VM_EXEC_OK
        }
        Err(message) => {
            with_service(|service| service.update_last_error_str(message.to_string()));
            vm_exec_result_t::VM_EXEC_ERROR
        }
    }
}

/// Calls an exported function of a WebAssembly instance by `name`
/// with the provided parameters. The exported function results are
/// stored on the provided `results` pointer.
///
/// This function returns `vm_exec_result_t::WASMER_OK` upon success,
/// `vm_exec_result_t::WASMER_ERROR` otherwise. You can use
/// `wasmer_last_error_message()` to get the generated error message.
///
/// Potential errors are the following:
///
///   * `instance` is a null pointer,
///   * `name` is a null pointer,
///   * `params` is a null pointer.
///
/// # Safety
///
/// C API function, works with raw object pointers.
#[allow(clippy::cast_ptr_alignment)]
#[unsafe(no_mangle)]
#[capi_safe_unwind(vm_exec_result_t::VM_EXEC_ERROR)]
pub unsafe extern "C" fn vm_exec_instance_call(
    instance_ptr: *mut vm_exec_instance_t,
    func_name_ptr: *const c_char,
) -> vm_exec_result_t {
    let capi_instance = cast_capi_instance_ptr!(instance_ptr);

    // unpack the function name
    if func_name_ptr.is_null() {
        with_service(|service| service.update_last_error_str("name ptr is null".to_string()));
        return vm_exec_result_t::VM_EXEC_ERROR;
    }
    let func_name_r = match unsafe { read_bounded_c_str(func_name_ptr) } {
        Ok(name) => name,
        Err(err) => {
            with_service(|service| service.update_last_error_str(err));
            return vm_exec_result_t::VM_EXEC_ERROR;
        }
    };

    let result = capi_instance.content.call(func_name_r);
    match result {
        Ok(()) => vm_exec_result_t::VM_EXEC_OK,
        Err(message) => {
            with_service(|service| service.update_last_error_str(message));
            vm_exec_result_t::VM_EXEC_ERROR
        }
    }
}

/// Checks that all public module functions (SC endpoints) have no arguments or results.
///
/// Still in the works.
///
/// # Safety
///
/// C API function, works with raw object pointers.
#[allow(clippy::cast_ptr_alignment)]
#[unsafe(no_mangle)]
#[capi_safe_unwind(vm_exec_result_t::VM_EXEC_ERROR)]
pub unsafe extern "C" fn vm_check_signatures(
    instance_ptr: *mut vm_exec_instance_t,
) -> vm_exec_result_t {
    let capi_instance = cast_capi_instance_ptr!(instance_ptr);
    if capi_instance.content.check_signatures() {
        vm_exec_result_t::VM_EXEC_OK
    } else {
        with_service(|service| {
            service.update_last_error_str(
                "non-zero number of params or results for at least one endpoint".to_string(),
            )
        });
        vm_exec_result_t::VM_EXEC_ERROR
    }
}

/// Checks whether SC has an endpoint with given name.
///
/// # Safety
///
/// C API function, works with raw object pointers.
#[allow(clippy::cast_ptr_alignment)]
#[unsafe(no_mangle)]
#[capi_safe_unwind(-1)]
pub unsafe extern "C" fn vm_exec_instance_has_function(
    instance_ptr: *mut vm_exec_instance_t,
    func_name_ptr: *const c_char,
) -> c_int {
    let capi_instance = cast_capi_instance_ptr!(instance_ptr, -1);

    // unpack the function name
    return_if_ptr_null!(func_name_ptr, "function name ptr is null", -1);
    let func_name_r = match unsafe { read_bounded_c_str(func_name_ptr) } {
        Ok(name) => name,
        Err(err) => {
            with_service(|service| service.update_last_error_str(err));
            return -1;
        }
    };

    c_int::from(capi_instance.content.has_function(func_name_r))
}

/// Checks whether SC has an endpoint with given name.
///
/// # Safety
///
/// C API function, works with raw object pointers.
#[allow(clippy::cast_ptr_alignment)]
#[unsafe(no_mangle)]
#[capi_safe_unwind(-1)]
pub unsafe extern "C" fn vm_exec_instance_has_imported_function(
    instance_ptr: *mut vm_exec_instance_t,
    func_name_ptr: *const c_char,
) -> c_int {
    let capi_instance = cast_capi_instance_ptr!(instance_ptr, -1);

    // unpack the function name
    return_if_ptr_null!(func_name_ptr, "function name ptr is null", -1);
    let func_name_r = match unsafe { read_bounded_c_str(func_name_ptr) } {
        Ok(name) => name,
        Err(err) => {
            with_service(|service| service.update_last_error_str(err));
            return -1;
        }
    };

    c_int::from(capi_instance.content.has_imported_function(func_name_r))
}

/// Required to be able to extract all SC endpoint names. See `vm_exported_function_names`.
///
/// # Safety
///
/// C API function, works with raw object pointers.
#[allow(clippy::cast_ptr_alignment)]
#[unsafe(no_mangle)]
#[capi_safe_unwind(0)]
pub unsafe extern "C" fn vm_exported_function_names_length(
    instance_ptr: *mut vm_exec_instance_t,
) -> c_int {
    let capi_instance = cast_capi_instance_ptr!(instance_ptr, 0);

    let func_names = capi_instance.content.get_exported_function_names();
    if func_names.is_empty() {
        0
    } else {
        let len_sum: usize = func_names.iter().map(|func_name| func_name.len()).sum();
        c_int::try_from(len_sum + func_names.len()).unwrap_or(0)
    }
}

/// Returns all SC endpoint names, separated by pipes.
///
/// e.g. `"init|endpoint1|endpoint2"`
///
/// No endpoint order is assumed.
///
/// It is necessary to first call `vm_exported_function_names_length` and pre-allocate a buffer of this length.
///
/// # Safety
///
/// C API function, works with raw object pointers.
#[allow(clippy::cast_ptr_alignment)]
#[unsafe(no_mangle)]
#[capi_safe_unwind(0)]
pub unsafe extern "C" fn vm_exported_function_names(
    instance_ptr: *mut vm_exec_instance_t,
    dest_buffer: *mut c_char,
    dest_buffer_len: c_int,
) -> c_int {
    let capi_instance = cast_capi_instance_ptr!(instance_ptr, 0);

    let func_names = capi_instance.content.get_exported_function_names();
    let concat = func_names.join("|");
    unsafe { string_copy(concat, dest_buffer, dest_buffer_len) }
}

/// Frees memory for the given `vm_exec_instance_t`.
///
/// Check the `wasmer_instantiate()` function to get a complete
/// example.
///
/// If `instance` is a null pointer, this function does nothing.
///
/// # Safety
///
/// C API function, works with raw object pointers.
#[allow(clippy::cast_ptr_alignment)]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn vm_exec_instance_destroy(instance_ptr: *mut vm_exec_instance_t) {
    if instance_ptr.is_null() {
        return;
    }
    // SAFETY contract — race-protection, NOT stale-pointer-protection.
    //
    // The Acquire load below works correctly only when the
    // CapiInstance allocation is still live (i.e. the first destroy
    // has either not happened yet or is racing this one). It does
    // NOT protect a second destroy from a single thread after the
    // first destroy has completed: by then the allocation has been
    // reclaimed by Box::from_raw and the read on the next line is
    // undefined behaviour regardless of what the freed memory still
    // contains.
    //
    // Acceptable usage contract for the Go-side caller:
    //   - Concurrent destroys from multiple goroutines on the same
    //     pointer are safe; only one wins the cmpxchg and reclaims.
    //   - A single thread must never call destroy twice on the same
    //     pointer. The destroyed flag does not (and structurally
    //     cannot) protect that case.
    //
    // The complete fix is the handle-based API redesign tracked as
    // audit Open Finding #3. See the CapiInstance::destroyed field
    // doc-comment for details.
    let inst_ref = unsafe { &*(instance_ptr as *const CapiInstance) };
    if inst_ref
        .destroyed
        .compare_exchange(false, true, Ordering::AcqRel, Ordering::Acquire)
        .is_err()
    {
        // Already destroyed (or being destroyed concurrently). Do
        // nothing — the first caller wins the race and owns the
        // reclamation.
        return;
    }
    let instance = unsafe { Box::from_raw(instance_ptr as *mut CapiInstance) };
    drop(instance);
}

/// Resets an instance, cleaning memories and globals.
///
/// # Safety
///
/// C API function, works with raw object pointers.
#[allow(clippy::cast_ptr_alignment)]
#[unsafe(no_mangle)]
#[capi_safe_unwind(vm_exec_result_t::VM_EXEC_ERROR)]
pub unsafe extern "C" fn vm_exec_instance_reset(
    instance_ptr: *mut vm_exec_instance_t,
) -> vm_exec_result_t {
    let capi_instance = cast_capi_instance_ptr!(instance_ptr);

    let result = capi_instance.content.reset();
    match result {
        Ok(()) => vm_exec_result_t::VM_EXEC_OK,
        Err(message) => {
            with_service(|service| service.update_last_error_str(message));
            vm_exec_result_t::VM_EXEC_ERROR
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::service_singleton::with_service;
    use multiversx_chain_vm_executor::{BreakpointValueLegacy, ExecutorError, MemLength, MemPtr};

    struct MockInstance;

    impl InstanceLegacy for MockInstance {
        fn call(&self, _func_name: &str) -> Result<(), String> {
            Ok(())
        }

        fn check_signatures(&self) -> bool {
            true
        }

        fn has_function(&self, _func_name: &str) -> bool {
            panic!("invalid UTF-8 must be rejected before instance dispatch")
        }

        fn has_imported_function(&self, _func_name: &str) -> bool {
            panic!("invalid UTF-8 must be rejected before instance dispatch")
        }

        fn get_exported_function_names(&self) -> Vec<String> {
            Vec::new()
        }

        fn set_points_limit(&self, _limit: u64) -> Result<(), String> {
            Ok(())
        }

        fn set_points_used(&self, _points: u64) -> Result<(), String> {
            Ok(())
        }

        fn get_points_used(&self) -> Result<u64, String> {
            Ok(0)
        }

        fn memory_length(&self) -> Result<u64, String> {
            Ok(0)
        }

        fn memory_ptr(&self) -> Result<*mut u8, String> {
            Ok(std::ptr::null_mut())
        }

        fn memory_load(
            &self,
            _mem_ptr: MemPtr,
            _mem_length: MemLength,
        ) -> Result<&[u8], ExecutorError> {
            Ok(&[])
        }

        fn memory_store(&self, _mem_ptr: MemPtr, _data: &[u8]) -> Result<(), ExecutorError> {
            Ok(())
        }

        fn memory_grow(&self, _by_num_pages: u32) -> Result<u32, ExecutorError> {
            Ok(0)
        }

        fn set_breakpoint_value(&self, _value: BreakpointValueLegacy) -> Result<(), String> {
            Ok(())
        }

        fn get_breakpoint_value(&self) -> Result<BreakpointValueLegacy, String> {
            Ok(BreakpointValueLegacy::None)
        }

        fn reset(&self) -> Result<(), String> {
            Ok(())
        }

        fn cache(&self) -> Result<Vec<u8>, String> {
            Ok(Vec::new())
        }
    }

    fn new_mock_instance_ptr() -> *mut vm_exec_instance_t {
        Box::into_raw(Box::new(CapiInstance {
            content: Box::new(MockInstance),
            destroyed: AtomicBool::new(false),
        })) as *mut vm_exec_instance_t
    }

    fn assert_invalid_utf8_error() {
        let last_error = with_service(|service| service.get_last_error_string());
        assert!(last_error.starts_with("invalid function name utf-8:"));
    }

    #[test]
    fn vm_exec_instance_has_function_rejects_invalid_utf8() {
        let instance_ptr = new_mock_instance_ptr();
        let invalid_name = [0xff_u8, 0x00];

        let result = unsafe {
            vm_exec_instance_has_function(instance_ptr, invalid_name.as_ptr() as *const c_char)
        };

        assert_eq!(result, -1);
        assert_invalid_utf8_error();
        unsafe { vm_exec_instance_destroy(instance_ptr) };
    }

    #[test]
    fn vm_exec_instance_has_imported_function_rejects_invalid_utf8() {
        let instance_ptr = new_mock_instance_ptr();
        let invalid_name = [0xff_u8, 0x00];

        let result = unsafe {
            vm_exec_instance_has_imported_function(
                instance_ptr,
                invalid_name.as_ptr() as *const c_char,
            )
        };

        assert_eq!(result, -1);
        assert_invalid_utf8_error();
        unsafe { vm_exec_instance_destroy(instance_ptr) };
    }
}
